# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: webhook-notification
spec:
  enabled: true
  requires: ">=2.23.0"
  settingName: webhook-notification-settings
  configMapName: webhook-notification-configmap
  author:
    name: ziyoung
    website: https://ziyoung.top
  logo: logo.png
  homepage: https://github.com/bq60t/plugin-webhook-notification#readme
  repo: https://github.com/bq60t/plugin-webhook-notification
  issues: https://github.com/bq60t/plugin-webhook-notification/issues
  displayName: "Webhook 通知"
  description: "为 Halo 常见事件发送可配置的 Webhook 通知"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/bq60t/plugin-webhook-notification/blob/main/LICENSE"
